<a href="https://colab.research.google.com/github/ahmadhlawa/palestine-food-security-analysis/blob/main/notebooks/EDA1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Suite of Food Security Indicators

In [8]:
df_fs = pd.read_csv('https://raw.githubusercontent.com/ahmadhlawa/palestine-food-security-analysis/refs/heads/main/data/Suite%20of%20Food%20Security%20Indicators.csv')

display(df_fs.head())

df_fs.info()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,FS,Suite of Food Security Indicators,275,Palestine,6126,Value,22013,"Gross domestic product per capita, PPP, (const...",2000,2000,Int$/cap,4521,X,Figure from external organization,NaN
1,FS,Suite of Food Security Indicators,275,Palestine,6126,Value,22013,"Gross domestic product per capita, PPP, (const...",2001,2001,Int$/cap,3997,X,Figure from external organization,NaN
2,FS,Suite of Food Security Indicators,275,Palestine,6126,Value,22013,"Gross domestic product per capita, PPP, (const...",2002,2002,Int$/cap,3409,X,Figure from external organization,NaN
3,FS,Suite of Food Security Indicators,275,Palestine,6126,Value,22013,"Gross domestic product per capita, PPP, (const...",2003,2003,Int$/cap,3789,X,Figure from external organization,NaN
4,FS,Suite of Food Security Indicators,275,Palestine,6126,Value,22013,"Gross domestic product per capita, PPP, (const...",2004,2004,Int$/cap,4503,X,Figure from external organization,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 882 entries, 0 to 881
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Domain Code       882 non-null    object
 1   Domain            882 non-null    object
 2   Area Code (M49)   882 non-null    int64
 3   Area              882 non-null    object
 4   Element Code      882 non-null    int64
 5   Element           882 non-null    object
 6   Item Code         882 non-null    object
 7   Item              882 non-null    object
 8   Year Code         882 non-null    int64
 9   Year              882 non-null    object
 10  Unit              860 non-null    object
 11  Value             764 non-null    object
 12  Flag              882 non-null    object
 13  Flag Description  882 non-null    object
 14  Note              254 non-null    object
dtypes: int64(3), object(12)
memory usage: 103.5+ KB

In [9]:
df_fs['Value'] = df_fs['Value'].astype(str).str.replace('<', '').str.replace('>', '').str.replace(',', '')
df_fs['Value'] = pd.to_numeric(df_fs['Value'], errors='coerce')
df_fs['Year'] = df_fs['Year'].astype(str)

df_fs_clean = df_fs.dropna(subset=['Value'])


print(df_fs_clean[['Year', 'Value']].isnull().sum())

display(df_fs_clean[['Item', 'Year', 'Value']].head())

Year     0
Value    0
dtype: int64

                                                Item  Year   Value
0  Gross domestic product per capita, PPP, (const...  2000  4521.0
1  Gross domestic product per capita, PPP, (const...  2001  3997.0
2  Gross domestic product per capita, PPP, (const...  2002  3409.0
3  Gross domestic product per capita, PPP, (const...  2003  3789.0
4  Gross domestic product per capita, PPP, (const...  2004  4503.0

In [10]:

df_fs_clean['Year'] = df_fs_clean['Year'].astype(str).str.split('-').str[-1].astype(int)


df_fs_pivot = df_fs_clean.pivot_table(index='Year', columns='Item', values='Value').reset_index()

print("شكل الجدول الجديد (الصفوف، الأعمدة):", df_fs_pivot.shape)
print("\nأول 5 صفوف بعد تحويل المؤشرات إلى أعمدة:")
display(df_fs_pivot.head())

print("\nقائمة المؤشرات التي أصبحت أعمدة:")
print(df_fs_pivot.columns.tolist())

شكل الجدول الجديد (الصفوف، الأعمدة): (25, 37)

أول 5 صفوف بعد تحويل المؤشرات إلى أعمدة:

/tmp/ipykernel_7750/2089576929.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fs_clean['Year'] = df_fs_clean['Year'].astype(str).str.split('-').str[-1].astype(int)

Item,Year,Average dietary energy requirement (kcal/cap/day),"Gross domestic product per capita, PPP, (constant 2021 international $)",Incidence of caloric losses at retail distribution level (percent),Minimum dietary energy requirement (kcal/cap/day),Number of children under 5 years affected by wasting (million),Number of children under 5 years of age who are overweight (modeled estimates) (million),Number of children under 5 years of age who are stunted (modeled estimates) (million),Number of moderately or severely food insecure female adults (million) (3-year average),Number of moderately or severely food insecure male adults (million) (3-year average),...,Prevalence of exclusive breastfeeding among infants 0-5 months of age (percent),Prevalence of low birthweight (percent),Prevalence of moderate or severe food insecurity in the female adult population (percent) (3-year average),Prevalence of moderate or severe food insecurity in the male adult population (percent) (3-year average),Prevalence of moderate or severe food insecurity in the total population (percent) (3-year average),Prevalence of obesity in the adult population (18 years and older) (percent),Prevalence of severe food insecurity in the female adult population (percent) (3-year average),Prevalence of severe food insecurity in the male adult population (percent) (3-year average),Prevalence of severe food insecurity in the total population (percent) (3-year average),Value of food imports in total merchandise exports (percent) (3-year average)
0,2000,2132.0,4521.0,3.01,1660.0,0.1,0.1,0.1,NaN,NaN,...,NaN,9.0,NaN,NaN,NaN,27.3,NaN,NaN,NaN,NaN
1,2001,2138.0,3997.0,3.00,1665.0,NaN,0.1,0.1,NaN,NaN,...,NaN,9.1,NaN,NaN,NaN,28.0,NaN,NaN,NaN,NaN
2,2002,2145.0,3409.0,3.00,1669.0,0.1,0.1,0.1,NaN,NaN,...,NaN,9.2,NaN,NaN,NaN,28.7,NaN,NaN,NaN,103.0
3,2003,2152.0,3789.0,3.00,1673.0,NaN,0.1,0.1,NaN,NaN,...,NaN,9.3,NaN,NaN,NaN,29.4,NaN,NaN,NaN,118.0
4,2004,2160.0,4503.0,2.99,1678.0,0.1,0.1,0.1,NaN,NaN,...,NaN,9.3,NaN,NaN,NaN,30.0,NaN,NaN,NaN,121.0

قائمة المؤشرات التي أصبحت أعمدة:
['Year', 'Average dietary energy requirement (kcal/cap/day)', 'Gross domestic product per capita, PPP, (constant 2021 international $)', 'Incidence of caloric losses at retail distribution level (percent)', 'Minimum dietary energy requirement (kcal/cap/day)', 'Number of children under 5 years affected by wasting (million)', 'Number of children under 5 years of age who are overweight (modeled estimates) (million)', 'Number of children under 5 years of age who are stunted (modeled estimates) (million)', 'Number of moderately or severely food insecure female adults (million) (3-year average)', 'Number of moderately or severely food insecure male adults (million) (3-year average)', 'Number of moderately or severely food insecure people (million) (3-year average)', 'Number of newborns with low birthweight (million)', 'Number of obese adults (18 years and older) (million)', 'Number of severely food insecure female adults (million) (3-year average)', 'Number of severely food insecure male adults (million) (3-year average)', 'Number of severely food insecure people (million) (3-year average)', 'Number of women of reproductive age (15-49 years) affected by anemia (million)', 'Percent of arable land equipped for irrigation (percent) (3-year average)', 'Percentage of children under 5 years affected by wasting (percent)', 'Percentage of children under 5 years of age who are overweight (modelled estimates) (percent)', 'Percentage of children under 5 years of age who are stunted (modelled estimates) (percent)', 'Percentage of population using at least basic drinking water services (percent)', 'Percentage of population using at least basic sanitation services (percent)', 'Percentage of population using safely managed drinking water services (percent)', 'Percentage of population using safely managed sanitation services (percent)', 'Political stability and absence of violence/terrorism (index)', 'Prevalence of anemia among women of reproductive age (15-49 years) (percent)', 'Prevalence of exclusive breastfeeding among infants 0-5 months of age (percent)', 'Prevalence of low birthweight (percent)', 'Prevalence of moderate or severe food insecurity in the female adult population (percent) (3-year average)', 'Prevalence of moderate or severe food insecurity in the male adult population (percent) (3-year average)', 'Prevalence of moderate or severe food insecurity in the total population (percent) (3-year average)', 'Prevalence of obesity in the adult population (18 years and older) (percent)', 'Prevalence of severe food insecurity in the female adult population (percent) (3-year average)', 'Prevalence of severe food insecurity in the male adult population (percent) (3-year average)', 'Prevalence of severe food insecurity in the total population (percent) (3-year average)', 'Value of food imports in total merchandise exports (percent) (3-year average)']

In [11]:
df_fs.to_csv('Suite of Food Security Indicators_cleaned.csv', index=False)

# Data Cleaning & Structural Transformation: Food Security Indicators
In this stage, we processed the FAO Food Security dataset to make it compatible with machine learning models.

Value Normalization: Stripped non-numeric symbols (e.g., '<', '>', ',') and handled suppressed data by converting to numeric types and removing nulls.

Temporal Alignment: Cleaned the 'Year' column by resolving interval formats (e.g., 2018-2020) to single representative integers to allow merging with other datasets.

Feature Engineering (Pivoting): Transformed the data from a long format to a wide format, turning individual food security metrics into independent features (columns) for time-series analysis.